name: ci

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ (github.ref_name == 'main' && 'latest') || github.ref_name }}
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: consensys/geth-peer-sidecar:${{ env.TAG }}, consensys/geth-peer-sidecar:${{ github.sha }}
          platforms: |-
              linux/amd64
          pull: true
          cache-from: type=gha
          cache-to: type=gha
